// Enumeration
const ActionTypes = {
  // DATA
  RECEIVE_TICKERS_DATA: 'RECEIVE_TICKERS_DATA',
  RECEIVE_TRADING_DATA: 'RECEIVE_TRADING_DATA',
  CHANGE_COLUMN_VISIBILITY: 'CHANGE_COLUMN_VISIBILITY',

  // PORTFOLIO
  GET_PORTFOLIO: 'GET_PORTFOLIO',
  GET_PORTFOLIOS: 'GET_PORTFOLIOS',
  ADD_PORTFOLIO: 'ADD_PORTFOLIO',
  DELETE_PORTFOLIO: 'DELETE_PORTFOLIO',
  SELECT_PORTFOLIO: 'SELECT_PORTFOLIO',
  EDIT_PORTFOLIO: 'EDIT_PORTFOLIO',

  // USER
  OPEN_ADD_DIALOG: 'OPEN_ADD_DIALOG',
  CLOSE_ADD_DIALOG: 'CLOSE_ADD_DIALOG',
  OPEN_EDIT_DIALOG: 'OPEN_EDIT_DIALOG',
  CLOSE_EDIT_DIALOG: 'CLOSE_EDIT_DIALOG',
  OPEN_SYMBOLS_DIALOG: 'OPEN_SYMBOLS_DIALOG',
  CLOSE_SYMBOLS_DIALOG: 'CLOSE_SYMBOLS_DIALOG',
  TOGGLE_SETTINGS_PANEL: 'TOGGLE_SETTINGS_PANEL',

  // APP
  CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
  CHANGE_GRID_SECTION: 'CHANGE_GRID_SECTION',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
};

export default ActionTypes;
